# Generated by Django 6.0.6 on 2026-06-20 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 20, 11, 57, 55, 279331, tzinfo=datetime.timezone.utc)),
        ),
    ]
