# Generated by Django 6.0.6 on 2026-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
